
# This is needed so it searches the standard paths. There's no "default" values
ClientExitPath:
   ExitsDefaultPath=/var/mqm/exits
   ExitsDefaultPath64=/var/mqm/exits64

# Definition of the exit.
ApiExitLocal:
  Sequence=10
  Function=EntryPoint
  Module=mqinootel
  Name=MQNoOTelExit
