#****************************************************************************************#
#* Module name : mqclient.ini                                                           *#
#* Type        : IBM MQ client configuration file                                       *#
#* Function    : Define the client configuration                                        *#
#*                                                                                      *#
#****************************************************************************************#

SSL:
  AllowTLSV13=TRUE

ClientExitPath:
   ExitsDefaultPath=/var/mqm/exits
   ExitsDefaultPath64=/var/mqm/exits64

PreConnect:
  Module=chllog_r
  Function=PreconnectExit
  Data=ldap://myLDAPServer.com:389/cn=wmq,ou=ibm,ou=com
  Sequence=1
